services:
  ms-catalogo:
    image: ms-catalogo:v1.0.0
    container_name: ms-catalogo
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - catalogo.localhost
    environment:
      - CATALOGO_PORT=3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-catalogo.rule=Host(`catalogo.localhost`)"
      - "traefik.http.routers.ms-catalogo.tls=true"
      - "traefik.http.services.ms-catalogo.loadbalancer.server.port=3001"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true