services:
  ms-catalogo:
    image: ms-catalogo:1.0.0
    container_name: ms-catalogo
    env_file: [".env"]
    ports:
      - "3001:3001"
    networks:
      patronSaga-network:
        aliases:
          - catalogo.localhost
    environment:
      - CATALOGO_PORT=3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-catalogo.rule=PathPrefix(`/api/v1/catalogo`)"
      - "traefik.http.routers.ms-catalogo.entrypoints=http"
      - "traefik.http.services.ms-catalogo.loadbalancer.server.port=3001"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true