
services:
  ms-catalogo:
    build:
      context: ./ms-catalogo
      dockerfile: Dockerfile
    image: ms-catalogo:v1.0.0
    container_name: ms-catalogo
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - catalogo.localhost
    environment:
      - CATALOGO_PORT=3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-catalogo.rule=Host(`catalogo.localhost`)"
      - "traefik.http.routers.ms-catalogo.tls=true"
      - "traefik.http.services.ms-catalogo.loadbalancer.server.port=3001"
      - "traefik.docker.network=patronSaga-network"

  ms-compras:
    build:
      context: ./ms-compras
      dockerfile: Dockerfile
    image: ms-compras:v1.0.0
    container_name: ms-compras
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - compras.localhost
    environment:
      - COMPRAS_PORT=3002
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-compras.rule=Host(`compras.localhost`)"
      - "traefik.http.routers.ms-compras.tls=true"
      - "traefik.http.services.ms-compras.loadbalancer.server.port=3002"
      - "traefik.docker.network=patronSaga-network"

  ms-inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    image: ms-inventario:v1.0.0
    container_name: ms-inventario
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - inventario.localhost
    environment:
      - INVENTARIO_PORT=3003
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-inventario.rule=Host(`inventario.localhost`)"
      - "traefik.http.routers.ms-inventario.tls=true"
      - "traefik.http.services.ms-inventario.loadbalancer.server.port=3003"
      - "traefik.docker.network=patronSaga-network"

  ms-pagos:
    build:
      context: ./ms-pagos
      dockerfile: Dockerfile
    image: ms-pagos:v1.0.0
    container_name: ms-pagos
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - pagos.localhost
    environment:
      - PAGOS_PORT=3004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-pagos.rule=Host(`pagos.localhost`)"
      - "traefik.http.routers.ms-pagos.tls=true"
      - "traefik.http.services.ms-pagos.loadbalancer.server.port=3004"
      - "traefik.docker.network=patronSaga-network"

  ms-orquestador:
    build:
      context: ./ms-orquestador
      dockerfile: Dockerfile
    image: ms-orquestador:v1.0.0
    container_name: ms-orquestador
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - orquestador.localhost
    environment:
      - ORQUESTADOR_PORT=3000
      - CATALOGO_URL=http://ms-catalogo:3001
      - COMPRAS_URL=http://ms-compras:3002
      - INVENTARIO_URL=http://ms-inventario:3003
      - PAGOS_URL=http://ms-pagos:3004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-orquestador.rule=Host(`orquestador.localhost`)"
      - "traefik.http.routers.ms-orquestador.tls=true"
      - "traefik.http.services.ms-orquestador.loadbalancer.server.port=3000"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true


