services:
  ms-pagos:
    image: ms-pagos:1.0.0
    container_name: ms-pagos
    env_file: [".env"]
    ports:
      - "3004:3004"
    networks:
      patronSaga-network:
        aliases:
          - pagos.localhost
    environment:
      - PAGOS_PORT=3004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-pagos.rule=PathPrefix(`/api/v1/pago`)"
      - "traefik.http.routers.ms-pagos.entrypoints=http"
      - "traefik.http.services.ms-pagos.loadbalancer.server.port=3004"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true