services:
  ms-orquestador:
    image: ms-orquestador:v1.0.0
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - orquestador.localhost
    environment:
      - CATALOGO_URL=http://ms-catalogo:3001
      - COMPRAS_URL=http://ms-compras:3002
      - INVENTARIO_URL=http://ms-inventario:3003
      - PAGOS_URL=http://ms-pagos:3004
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms-orquestador.rule=Host(`orquestador.localhost`)"
      - "traefik.http.routers.ms-orquestador.tls=true"
      - "traefik.http.services.ms-orquestador.loadbalancer.server.port=3000"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true