services:
  ms-orquestador:
    image: ms-orquestador:1.0.0
    container_name: ms-orquestador
    env_file: [".env"]
    networks:
      patronSaga-network:
        aliases:
          - orquestador.localhost
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orquestador.rule=PathPrefix(`/api/v1/orquestador`)"
      - "traefik.http.routers.orquestador.entrypoints=http"
      - "traefik.http.services.orquestador.loadbalancer.server.port=3000"
      - "traefik.docker.network=patronSaga-network"

networks:
  patronSaga-network:
    name: patronSaga-network
    external: true